### ISSUE TITLE
Move away from Rails Assets

### ISSUE THREAD

**Issue by floriandejonckheere** [floriandejonckheere/thalariond#17]
Rails Assets is discontinuing active support after 2016: rails-assets/rails-assets#291.

**Comment by hut8** [comment]
Hey. If you're happy with how Rails Assets is working now, you can use the mirror that my consultancy is supporting indefinitely: https://rails-assets.tenex.tech. Thanks!

**Comment by floriandejonckheere** [comment]
Hi, thanks for the information. I'm rethinking the asset system anyway, so I'll probably just switch to something like Bower. But it's nice to see that Rails Assets won't be lost!
